### ISSUE TITLE
XL FOOD MOD , seems to be no way to get this mod started, ie how to get the seeds

### ISSUE THREAD

**Issue by sparitsa** [ResqDiver1317/ThirdPeril_PerilousSkies#21]
**Describe the bug**
A clear and concise description of what the bug is. Be sure to state what mod(s) this issue is related to.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash Reports**
If this is related to a crash, please upload your crash report (upload the actual crash report file, please do not copy/paste your crash report into this issue).

**Additional context**

**Comment by MunchNStuff** [comment]
These seeds are super rare in dungeon chest in the deep dark. I have only found two of them.
@ResqDiver1317 do you want me to add these seeds to the dirt sifting for diamond mesh?

**Comment by ResqDiver1317** [comment]
@MunchNStuff From looking at this in SP, we don't need to add the actual seeds to sieve. We just need a way to get the XL Food Grass which can then be placed on the ground and broken to get seed drops. In normal worlds, the grass would randomly grow around the world but since there isn't a world for it to generate in, simply making a way to obtain it should suffice. Adding the grass to be obtained sieving dirt oughta do it. Also need to obtain Vanilla flowers (the flavoring, not game style) and rock salt from what I can tell from looking at the CF page for the mod. Mekanism salt is Ore Dict'd for it but that is it's own process to go through. I'm thinking the XL Grass and Vanilla should be obtained via dirt sieve and salt via gravel. Also should have crafting recipes to make the XL grass and Vanilla Flowers for those that do not want to go the ExNihilo route. I'm thinking for the grass, craft together wheat seed/regular seed, melon seed, and pumpkin seed and get XL grass. Vanilla I'm thinking bottle of water and sugar.

**Comment by MunchNStuff** [comment]
@ResqDiver1317 Sounds good.

**Comment by ResqDiver1317** [comment]
Sieve Edits - https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/b93246b32dac56cffd8cc75a9c507b4c5778d99e

Recipe Edits - https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/30a061359e3a4bfdeaac41e39bb6af626b52b559

**Comment by ResqDiver1317** [comment]
New Sieve Commit cuz I made a typo in the code. https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/1b184e2ec5ee1b695a7626c438e017fff8fc2368

**Comment by ResqDiver1317** [comment]
Update Log - https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/cc6d6f395b6fe14b9d3cc9d5413c489a3a57b0ed
